# Generated by Django 2.0.6 on 2018-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_manage', '0004_auto_20180815_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='create_time',
            field=models.IntegerField(db_column='create_time', default=1534335415),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_time',
            field=models.IntegerField(db_column='update_time', default=1534335415),
        ),
    ]
