# Generated by Django 2.0.6 on 2018-08-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column_manage', '0002_auto_20180813_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='has_scrolling_image',
            field=models.BooleanField(db_column='has_scrolling_image', default=False, verbose_name='是否有轮播图'),
        ),
        migrations.AddField(
            model_name='columns',
            name='page_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '文本图片'), (2, '留言页面'), (3, '物流查询'), (4, '文章类型')], db_column='page_type', null=True, verbose_name='单页面类型'),
        ),
        migrations.AddField(
            model_name='columns',
            name='thumb_photo_id',
            field=models.CharField(blank=True, db_column='thumb_photo_id', max_length=255, null=True, verbose_name='小图片ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.IntegerField(db_column='create_time', default=1534234344, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='columns',
            name='columns_type',
            field=models.SmallIntegerField(choices=[(1, '导航栏目'), (2, '单网页'), (3, '菜单')], db_column='columns_type', verbose_name='菜单类型'),
        ),
        migrations.AlterField(
            model_name='columns',
            name='link',
            field=models.CharField(blank=True, db_column='link', max_length=1000, null=True, verbose_name='链接地址'),
        ),
    ]
