# Generated by Django 2.0.6 on 2018-08-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column_manage', '0003_auto_20180814_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.IntegerField(db_column='create_time', default=1534299143, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='columns',
            name='page_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '文本图片'), (2, '留言页面'), (3, '物流查询'), (4, '文章列表类型')], db_column='page_type', null=True, verbose_name='单页面类型'),
        ),
    ]
