# Generated by Django 2.0.6 on 2018-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('column_manage', '0004_auto_20180815_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnScrollingImage',
            fields=[
                ('scrolling_image_id', models.AutoField(db_column='scrolling_image_id', primary_key=True, serialize=False, verbose_name='滚动图ID')),
                ('columns_id', models.BigIntegerField(db_column='columns_id')),
                ('photo_id', models.CharField(blank=True, db_column='photo_id', max_length=255, null=True, verbose_name='图片ID')),
                ('file_size', models.CharField(db_column='file_size', max_length=255, verbose_name='文件大小')),
                ('resolution', models.CharField(db_column='resolution', max_length=255, verbose_name='分辨率')),
                ('file_type', models.CharField(db_column='file_type', max_length=255, verbose_name='文件类型')),
                ('status', models.CharField(db_column='status', max_length=255, verbose_name='状态')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='columns_id',
            field=models.BigIntegerField(blank=True, db_column='columns_id', null=True, verbose_name='所属栏目ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=models.TextField(blank=True, db_column='article_content', null=True, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.IntegerField(db_column='create_time', default=1534335415, verbose_name='创建时间'),
        ),
    ]
